---
development:
  dialect: postgres
  database: acacms
  user: postgres
  password: beewantplatform1
  host: localhost
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:beewantplatform1@localhost:5432/acacms_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:beewantplatform1@localhost:5432/acacms_production?sslmode=disable"}}
